# Generated by Django 3.0.7 on 2020-06-08 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sql', '0002_auto_20200607_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
